$(function(){$('.calc-menu a').on('click',function(e){e.preventDefault();var id=$(this).attr('href');$(id).show();$('.blk').not(id).hide();$(this).parent().addClass('active').siblings().removeClass('active')});var shir_balk_min=50;var shir_balk_max=120;var vysota_balk_min=50;var vysota_balk_max=200;var stoim=5200;var skidka=0.58;skidka=1-skidka;var montazhrab=1200;var podokonnik=600;var demontaj=500;var moskitka=700;var otliv=300;var laminat=5;var koeffits=1;var shirinafin=0;var costfin=0;var tipbalk=$('.thumb-bal li.active').data('tip');function delim(st){return parseInt(st).toString().replace(/(\d)(?=(\d\d\d)+([^\d]|$))/g,'$1 ')}
change_price();function change_price(){var dp=0;var costVert=$('#Costverbalk').val();$('#dop1 input').each(function(){if($(this).prop('checked')){switch($(this).attr('name')){case 'montaz':dp+=montazhrab;break;case 'demontaj':dp+=demontaj;break;case 'podokonnik':dp+=podokonnik;break;case 'moskitka':dp+=moskitka;break;case 'otliv':dp+=otliv;break}}});var res=0;$('.blk-field.visible input').each(function(index,element){res+=element.value*costVert*stoim/10000});costfin=res*koeffits*skidka+dp;costfin=Math.round(costfin);$('#costfin').html(delim(costfin))}
$('.thumb-bal a').on('click',function(e){e.preventDefault();var src=$(this).find('img').attr('src').replace('thumb-','');var thumb=$(this).parent().data('section');tipbalk=$(this).parent().data('tip');$(this).parent().addClass('active').siblings().removeClass('active');$('#bal-full').attr('src',src);$('.width-fields .blk-field').removeClass('visible');switch(thumb){case 1:$('#f1').addClass('visible');break;case 2:$('#f1, #f2').addClass('visible');break;case 3:$('#f1, #f2, #f3').addClass('visible');break;case 4:$('#f1, #f2, #f3, #f4').addClass('visible');break}
switch(tipbalk){case 1:$('#Costhor1').val('150');break;case 2:$('#Costhor1').val('100');$('#Costhor2').val('100');break;case 3:$('#Costhor1').val('50');$('#Costhor2').val('100');$('#Costhor3').val('50');break;case 4:$('#Costhor1').val('150');$('#Costhor2').val('50');$('#Costhor3').val('50');break;case 5:$('#Costhor1').val('50');$('#Costhor2').val('200');break;case 6:$('#Costhor1').val('50');$('#Costhor2').val('200');$('#Costhor3').val('50');break;case 7:$('#Costhor1').val('100');$('#Costhor2').val('50');$('#Costhor3').val('50');$('#Costhor4').val('50');break}
change_price()});$('.blk-field input, .param-inpt-text').on('keydown',function(event){var key,keyChar;if(!event)var event=window.event;if(event.keyCode)key=event.keyCode;else if(event.which)key=event.which;if(key==null||key==0||key==8||key==13||key==9||key==46||key==37||key==39||key==96||key==97||key==98||key==99||key==100||key==101||key==102||key==103||key==104||key==105)return!0;keyChar=String.fromCharCode(key);if(!/\d/.test(keyChar))return!1});$(".blk-field input").change(function(e){if($('#Costverbalk').val()<50){$('#Costverbalk').val('50')}else if($('#Costverbalk').val()>200){$('#Costverbalk').val('200')}
switch(tipbalk){case 1:if($('#Costhor1').val()<150){$('#Costhor1').val('150')}else if($('#Costhor1').val()>360){$('#Costhor1').val('360')}
break;case 2:if($('#Costhor1').val()<100){$('#Costhor1').val('100')}else if($('#Costhor1').val()>240){$('#Costhor1').val('240')}
if($('#Costhor2').val()<100){$('#Costhor2').val('100')}else if($('#Costhor2').val()>240){$('#Costhor2').val('240')}
break;case 3:if($('#Costhor1').val()<50){$('#Costhor1').val('50')}else if($('#Costhor1').val()>120){$('#Costhor1').val('120')}
if($('#Costhor2').val()<100){$('#Costhor2').val('100')}else if($('#Costhor2').val()>240){$('#Costhor2').val('240')}
if($('#Costhor3').val()<50){$('#Costhor3').val('50')}else if($('#Costhor3').val()>120){$('#Costhor3').val('120')}
break;case 4:if($('#Costhor1').val()<150){$('#Costhor1').val('150')}else if($('#Costhor1').val()>360){$('#Costhor1').val('360')}
if($('#Costhor2').val()<50){$('#Costhor2').val('50')}else if($('#Costhor2').val()>120){$('#Costhor2').val('120')}
if($('#Costhor3').val()<50){$('#Costhor3').val('50')}else if($('#Costhor3').val()>120){$('#Costhor3').val('120')}
break;case 5:if($('#Costhor1').val()<50){$('#Costhor1').val('50')}else if($('#Costhor1').val()>120){$('#Costhor1').val('120')}
if($('#Costhor2').val()<200){$('#Costhor2').val('200')}else if($('#Costhor2').val()>480){$('#Costhor2').val('480')}
break;case 6:if($('#Costhor1').val()<50){$('#Costhor1').val('50')}else if($('#Costhor1').val()>120){$('#Costhor1').val('120')}
if($('#Costhor2').val()<200){$('#Costhor2').val('200')}else if($('#Costhor2').val()>480){$('#Costhor2').val('480')}
if($('#Costhor3').val()<50){$('#Costhor3').val('50')}else if($('#Costhor3').val()>120){$('#Costhor3').val('120')}
break;case 7:if($('#Costhor1').val()<100){$('#Costhor1').val('100')}else if($('#Costhor1').val()>240){$('#Costhor1').val('240')}
if($('#Costhor2').val()<50){$('#Costhor2').val('50')}else if($('#Costhor2').val()>120){$('#Costhor2').val('120')}
if($('#Costhor3').val()<50){$('#Costhor3').val('50')}else if($('#Costhor3').val()>120){$('#Costhor3').val('120')}
if($('#Costhor4').val()<50){$('#Costhor4').val('50')}else if($('#Costhor4').val()>120){$('#Costhor4').val('120')}
break}
change_price()});$('#dop1 input').on('change',function(){change_price()});var slideV='.slider-v',slideH='.slider-h',inputHeight='[name="c-height"]',inputWidth='[name="c-width"]';var oneMaxH=220,oneMinH=35,oneMaxW=240,oneMinW=35,oneSetH=150,oneSetW=60;var twoMaxH=220,twoMinH=35,twoMaxW=240,twoMinW=70,twoSetH=150,twoSetW=120;var threeMaxH=220,threeMinH=35,threeMaxW=300,threeMinW=105,threeSetH=150,threeSetW=180;var fourMaxH=250,fourMinH=160,fourMaxW=300,fourMinW=140,fourSetH=220,fourSetW=140;var minH=35,maxH=220,minW=70,maxW=240,setH=150,setW=120,handle=$("#custom-handle"),handle2=$("#custom-handle2"),costWin=1.22,vertic,horizon,total=0,incPrice=$('#costwin');var profArray=['Socol','GreenTech','GreenEco','Novotex','KBE','BaZeL',];for(var i=profArray.length-1;i>=0;i--){$('#profile').append('<option value="'+profArray[i]+'">'+profArray[i]+'</option>')}
function checkActiveWin(){if($('#wb-6').prop('checked')){laminat=!0}else{laminat=!1}
$('.window-type__block_img').each(function(){if($(this).hasClass('active')){var $win_tp=$(this).data('win');var range=$(this).data('range');switch(range){case 'one':if($win_tp=='one_1'&&!laminat){BaZeL=2516;KBE=2554;Novotex=2356;GreenTech=2160;GreenEco=2615;Socol=7209}
if($win_tp=='one_1'&&laminat){BaZeL=2516+450;KBE=2554+464;Novotex=2356+457;GreenTech=2160+0;GreenEco=2615+479;Socol=7198}
if($win_tp=='one_2'&&!laminat){BaZeL=4873;KBE=5280;Novotex=4492;GreenTech=4164;GreenEco=4975;Socol=13609}
if($win_tp=='one_2'&&laminat){BaZeL=4873+1084;KBE=5280+1046;Novotex=4492+1043;GreenTech=4164+0;GreenEco=4975+933;Socol=13605}
if($win_tp=='one_3'&&!laminat){BaZeL=6008;KBE=5540;Novotex=4967;GreenTech=4620;GreenEco=5402;Socol=16408}
if($win_tp=='one_3'&&laminat){BaZeL=6008+818;KBE=5540+1419;Novotex=4967+803;GreenTech=4620+0;GreenEco=5402+847;Socol=16404}
break;case 'two':if($win_tp=='two_1'&&!laminat){BaZeL=4684;KBE=4465;Novotex=3928;GreenTech=3641;GreenEco=4269;Socol=12688}
if($win_tp=='two_1'&&laminat){BaZeL=4684+657;KBE=4465+967;Novotex=3928+627;GreenTech=3641+0;GreenEco=4269+724;Socol=12658}
if($win_tp=='two_2'&&!laminat){BaZeL=5652;KBE=5893;Novotex=5212;GreenTech=4819;GreenEco=5714;Socol=16585}
if($win_tp=='two_2'&&laminat){BaZeL=5652+1171;KBE=5893+1311;Novotex=5212+894;GreenTech=4819+0;GreenEco=5714+940;Socol=16562}
if($win_tp=='two_3'&&!laminat){BaZeL=2739;KBE=2821;Novotex=2516;GreenTech=2331;GreenEco=2791;Socol=8241}
if($win_tp=='two_3'&&laminat){BaZeL=2739+440;KBE=2821+420;Novotex=2516+412;GreenTech=2331+0;GreenEco=2791+437;Socol=8263}
break;case 'three':if($win_tp=='three_1'&&!laminat){BaZeL=3576;KBE=3668;Novotex=3263;GreenTech=3024;GreenEco=3609;Socol=10180}
if($win_tp=='three_1'&&laminat){BaZeL=3576+783;KBE=3668+759;Novotex=3263+521;GreenTech=3024+0;GreenEco=3609+552;Socol=10172}
if($win_tp=='three_2'&&!laminat){BaZeL=5344;KBE=5872;Novotex=5468;GreenTech=4528;GreenEco=5373;Socol=15994}
if($win_tp=='three_2'&&laminat){BaZeL=5344+1128;KBE=5872+883;Novotex=5468+852;GreenTech=4528+0;GreenEco=5373+911;Socol=16015}
if($win_tp=='three_3'&&!laminat){BaZeL=4482;KBE=4801;Novotex=4149;GreenTech=3847;GreenEco=4595;Socol=14100}
if($win_tp=='three_3'&&laminat){BaZeL=4482+831;KBE=4801+704;Novotex=4149+685;GreenTech=3847+0;GreenEco=4595+731;Socol=14031}
if($win_tp=='three_4'&&!laminat){BaZeL=4688;KBE=4909;Novotex=4079;GreenTech=3776;GreenEco=4491;Socol=12540}
if($win_tp=='three_4'&&laminat){BaZeL=4688+172;KBE=4909+688;Novotex=4079+670;GreenTech=3776+0;GreenEco=4491+713;Socol=12563}
break;case 'four':if($win_tp=='four_1'&&!laminat){BaZeL=3576;KBE=3668;Novotex=3263;GreenTech=3024;GreenEco=3609;Socol=10180}
if($win_tp=='four_1'&&laminat){BaZeL=3576+783;KBE=3668+759;Novotex=3263+521;GreenTech=3024+0;GreenEco=3609+552;Socol=10172}
if($win_tp=='four_2'&&!laminat){BaZeL=5344;KBE=5872;Novotex=5468;GreenTech=4528;GreenEco=5373;Socol=15994}
if($win_tp=='four_2'&&laminat){BaZeL=5344+1128;KBE=5872+883;Novotex=5468+852;GreenTech=4528+0;GreenEco=5373+911;Socol=16015}
if($win_tp=='four_3'&&!laminat){BaZeL=4482;KBE=4801;Novotex=4149;GreenTech=3847;GreenEco=4595;Socol=14100}
if($win_tp=='four_3'&&laminat){BaZeL=4482+831;KBE=4801+704;Novotex=4149+685;GreenTech=3847+0;GreenEco=4595+731;Socol=14031}
if($win_tp=='four_4'&&!laminat){BaZeL=4688;KBE=4909;Novotex=4079;GreenTech=3776;GreenEco=4491;Socol=12540}
if($win_tp=='four_4'&&laminat){BaZeL=4688+172;KBE=4909+688;Novotex=4079+670;GreenTech=3776+0;GreenEco=4491+713;Socol=12563}
break}}})}
checkActiveWin();$('#wb-6').on('change',function(){checkActiveWin()});$('.window-type__block_img').on('click',function(){$('.window-type__block_img').removeClass('active');var actWin=$(this).addClass('active');var at=$(this).find('img').attr('src');var dtImg=$(this).data('img');$(this).siblings('.window-type__block_preview').find('img').attr('src',at);$('.window-type__block').removeClass('active');$(this).parent('.window-type__block').addClass('active');$('#img-action').find('img').attr('src','img/win/'+dtImg);var $win_tp=$(this).data('win');var range=$(this).data('range');switch(range){case 'one':minH=oneMinH;maxH=oneMaxH;minW=oneMinW;maxW=oneMaxW;setH=oneSetH;setW=oneSetW;$(slideV).slider("option",{value:setH,min:minH,max:maxH});$(slideH).slider("option",{value:setW,min:minW,max:maxW});$(inputHeight).val(setH);$(inputWidth).val(setW);vertic=setH;horizon=setW;break;case 'two':minH=twoMinH;maxH=twoMaxH;minW=twoMinW;maxW=twoMaxW;setH=twoSetH;setW=twoSetW;$(slideV).slider("option",{value:setH,min:minH,max:maxH});$(slideH).slider("option",{value:setW,min:minW,max:maxW});$(inputHeight).val(setH);$(inputWidth).val(setW);vertic=setH;horizon=setW;break;case 'three':minH=threeMinH;maxH=threeMaxH;minW=threeMinW;maxW=threeMaxW;setH=threeSetH;setW=threeSetW;$(slideV).slider("option",{value:setH,min:minH,max:maxH});$(slideH).slider("option",{value:setW,min:minW,max:maxW});$(inputHeight).val(setH);$(inputWidth).val(setW);vertic=setH;horizon=setW;break;case 'four':minH=fourMinH;maxH=fourMaxH;minW=fourMinW;maxW=fourMaxW;setH=fourSetH;setW=fourSetW;$(slideV).slider("option",{value:setH,min:minH,max:maxH});$(slideH).slider("option",{value:setW,min:minW,max:maxW});$(inputHeight).val(setH);$(inputWidth).val(setW);vertic=setH;horizon=setW;break}
checkActiveWin();calc()});var handleChangeInput=function(){$(inputHeight).change(function(){var value=$(this).val();if(value<minH){$(slideV).slider('value',minH);$(inputHeight).val(minH);vertic=parseInt(minH);calc()}else if(value>maxH){$(slideV).slider('value',maxH);$(inputHeight).val(maxH);vertic=parseInt(maxH);calc()}else{$(slideV).slider('value',value);vertic=parseInt(value);calc()}});$(inputWidth).change(function(){var value=$(this).val();if(value<minW){$(slideH).slider('value',minW);$(inputWidth).val(minW);horizon=parseInt(minW);calc()}else if(value>maxW){$(slideH).slider('value',maxW);$(inputWidth).val(maxW);horizon=parseInt(maxW);calc()}else{$(slideH).slider('value',value);horizon=parseInt(value);calc()}})};$(slideV).slider({orientation:'vertical',range:"min",min:minH,max:maxH,value:setH,create:function(event,ui){vertic=$(slideV).slider("value")},slide:function(event,ui){$(inputHeight).val(ui.value);handle.text(ui.value);vertic=ui.value;calc()}});$(inputHeight).val($(slideV).slider("value"));$(slideH).slider({orientation:'horizontal',range:"min",min:minW,max:maxW,value:setW,create:function(event,ui){horizon=$(slideH).slider("value")},slide:function(event,ui){$(inputWidth).val(ui.value);handle2.text(ui.value);horizon=ui.value;calc()}});$(inputWidth).val($(slideH).slider("value"));var elem2=!0;var elem=document.getElementById('cnt');if(elem2){var btnPlus=document.querySelector('.param-btn-plus'),btnMinus=document.querySelector('.param-btn-minus');btnPlus.addEventListener('click',function(){var cnt=elem.value;if(cnt<9)cnt++;elem.value=cnt});btnMinus.addEventListener('click',function(){var cnt=elem.value;if(cnt>1)cnt--;elem.value=cnt})}
function calc(){handleChangeInput();var dop=0;var lam=0;var profil;var quantity=$('#cnt').val();$('#profile').each(function(){var proff=$(this).val();var prof=eval($(this).val());profil=prof;if($(this).val()=='GreenTech'){$('#lam-info').text('ЛАМИНАЦИИ НЕ БЫВАЕТ');$('#wb-6').attr('disabled','disabled');$('label[for="wb-6"]').css('text-decoration','line-through')}else{$('#lam-info').text('');$('#wb-6').removeAttr('disabled');$('label[for="wb-6"]').css('text-decoration','none')}});$('#dop2 input').each(function(){if($(this).prop('checked')){switch($(this).attr('name')){case 'montaz':dop+=montazhrab;break;case 'demontaj':dop+=demontaj;break;case 'podokonnik':dop+=podokonnik;break;case 'moskitka':dop+=moskitka;break;case 'otliv':dop+=otliv;break}}});total=vertic*horizon;parseInt(total=total*profil/10000+dop);incPrice.html(delim(Math.round(total*quantity)))}
calc();$('.param button').on('click',function(){calc()});$('#dop2 input').on('change',function(){calc()});$('#profile').on('change',function(){calc()});$('#cnt').on('change',function(){calc()});$(".main_form").submit(function(e){var isValid=!0;$(this).find('input[type="text"]').each(function(){if($.trim($(this).val())==''){isValid=!1;$(this).css({"border":"1px solid red","background":"#FFCECE"})}else{$(this).css({"border":"","background":""})}});if(isValid==!1){e.preventDefault()}else{$.ajax({type:"POST",url:"mail.php",data:$(this).serialize()}).done(function(){$('.hidden, .popup').removeClass('active');$('#sent, .sent').addClass('active');setTimeout(function(){$(".main_form").trigger("reset")},1000)})}
return!1});$(".main_form").keydown(function(){$('input[type="text"]').each(function(){$(this).css({"border":"","background":""})})});$('.modalka').on('click',function(e){e.preventDefault();var id=$(this).attr('href');$(id).addClass('active');$(id).find('.popup').addClass('active')});$('.head-close, .cross2').on('click',function(e){e.preventDefault();$('.popup, .hiden').removeClass('active');setTimeout(function(){$(".added").remove()},1000)});$('.cross2').on('click',function(e){e.preventDefault();$('.hiden, .sent').removeClass('active')})});$('.modalka').on('click',function(e){if($('.calc-menu li').first().hasClass('active')){var at=$('.window-type__block_img.active').data('value');var counts=$('#cnt').val();$('.pop-body').prepend('<h4 class="added">Стоимость: '+$('#costwin').html()+' Руб</h4>');$('#dop2 input').each(function(){if($(this).prop('checked')){var nm=$(this).attr('name');var ddp=$(this).next('label').html();$('.pop-body').prepend('<p class="added">Дополнительно: <span><b>'+ddp+'</b></span></p>');$('.pop-body form').prepend('<input class="added" type="hidden" name="'+nm+'" value="'+ddp+'">')}});$('.pop-body').prepend('<p class="added">Колличество изделий: <b>'+counts+'</b></p>');$('.pop-body').prepend('<p class="added"><span>Ширина: <b>'+$('.slider-h').slider("value")+' см</b></span> - <span class="added">Высота: <b>'+$('.slider-v').slider("value")+' см</b></span></p>');$('.pop-body').prepend('<p class="added">Название профиля: <b>'+$('#profile').val()+'</b></p>');$('.pop-body').prepend('<p class="added">Тип окна: <b>'+at+'</b></p>');$('.pop-body form').prepend('<input class="added" type="hidden" name="img" value="'+at+'">');$('.pop-body form').prepend('<input class="added" type="hidden" name="quantity" value="'+counts+'">');$('.pop-body form').prepend('<input class="added" type="hidden" name="width" value="'+$('.slider-h').slider("value")+'">');$('.pop-body form').prepend('<input class="added" type="hidden" name="height" value="'+$('.slider-v').slider("value")+'">');$('.pop-body form').prepend('<input class="added" type="hidden" name="prof_name" value="'+$('#profile').val()+'">');$('.pop-body form').prepend('<input class="added" type="hidden" name="cost" value="'+$('#costwin').html()+' Руб">')}else{var tip;var costfn=$('#costfin').html();$('.pop-body').prepend('<h4 class="added">Стоимость: '+costfn+' Руб</h4>');$('.thumb-bal li').each(function(){if($(this).hasClass('active')){tip=$(this).data('tp')}});$('#dop1 input').each(function(){if($(this).prop('checked')){var nmBal=$(this).attr('name');var ddpBal=$(this).next('label').html();$('.pop-body').prepend('<p class="added">Дополнительно: <span><b>'+ddpBal+'</b></span></p>');$('.pop-body form').prepend('<input class="added" type="hidden" name="'+nmBal+'" value="'+ddpBal+'">')}});jQuery.fn.reverseEach=(function(){var list=jQuery([1]);return function(c){var el,i=this.length;try{while(i-->0&&(el=list[0]=this[i])&&c.call(list,i,el)!==!1);}catch(e){delete list[0];throw e}
delete list[0];return this}}());$(".blk-field.visible").reverseEach(function(i){i++;$('.pop-body').prepend('<p class="added">Ширина секции '+i+': <b>'+$(this).find('input').val()+' см</b></p>');$('.pop-body form').prepend('<input class="added" type="hidden" name="width'+i+'" value="'+$(this).find('input').val()+'">')});$('.pop-body').prepend('<p class="added">Высота: <b>'+$("#Costverbalk").val()+' см</b></p>');$('.pop-body').prepend('<p class="added">Тип балкона: <b>'+tip+'</b></p>');$('.pop-body form').prepend('<input class="added" type="hidden" name="img" value="'+tip+'">');$('.pop-body form').prepend('<input class="added" type="hidden" name="height" value="'+$("#Costverbalk").val()+'">');$('.pop-body form').prepend('<input class="added" type="hidden" name="cost" value="'+costfn+' Руб">')}})